spring:
  application:
    name: InstaHub
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/instaHub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 1800000
  refresh:
    token:
      expiration: 1209600000

cloud:
  aws:
    s3:
      bucketName: ${BUCKET_NAME}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
      auto: true
    stack:
      auto: true

server:
  port: 8080